server:
  port: 8000


# MySQL
spring:
  datasource:
    url: jdbc:mysql://112.175.184.61:3306/miraclestep01?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: miraclestep01
    password: tndnqja11!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    remote:
      restart:
        enabled: true